[codegen] fix compilation with CLANG 15 on macOS
Prior to this fix, compiling Kudu with CLANG 15 on macOS Sonoma
would fail with an error like below:

  [..%] Generating precompiled.ll
  In file included from src/kudu/codegen/precompiled.cc:39:
  In file included from src/kudu/common/rowblock.h:21:
  ...
  /Applications/Xcode-15.3.0.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.4.sdk/usr/include/c++/v1/cstdlib:144:9: error: no member named 'at_quick_exit' in the global namespace
  using ::at_quick_exit _LIBCPP_USING_IF_EXISTS;
	~~^
  /Applications/Xcode-15.3.0.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.4.sdk/usr/include/c++/v1/cstdlib:145:9: error: no member named 'quick_exit' in the global namespace
  using ::quick_exit _LIBCPP_USING_IF_EXISTS;

Change-Id: Ibe92b7f00fdd446010cea1bda5fd25868a9acabc
Reviewed-on: http://gerrit.cloudera.org:8080/21232
Reviewed-by: Abhishek Chennaka <achennaka@cloudera.com>
Tested-by: Alexey Serbin <alexey@apache.org>
(cherry picked from commit 3a856f4502a29f26bb8c9b10a17b06eb16892d02)
Reviewed-on: http://gerrit.cloudera.org:8080/21790
Reviewed-by: Alexey Serbin <alexey@apache.org>
Tested-by: Abhishek Chennaka <achennaka@cloudera.com>