[build] Fix the directory creation
Fixes the recursive directory creation which according to
python documentation [1] should be os.makedirs() and not
os.path.makedirs() which results in the below error:
AttributeError: module 'posixpath' has no attribute 'makedirs'

1.
https://docs.python.org/2.6/library/os.html#os.makedirs
https://docs.python.org/3.11/library/os.html#os.makedirs

Change-Id: Ifef12fd681050c5d1e6841070fdd754a7d436f8f
Reviewed-on: http://gerrit.cloudera.org:8080/21883
Reviewed-by: Alexey Serbin <alexey@apache.org>
Tested-by: Marton Greber <greber.mx@gmail.com>
Reviewed-by: Marton Greber <greber.mx@gmail.com>
(cherry picked from commit c32708d5b957514420aaa13953c25db8940fe7cb)
Reviewed-on: http://gerrit.cloudera.org:8080/21890
Tested-by: Abhishek Chennaka <achennaka@cloudera.com>