[tests] fix a misprint
Tests should use ASSERT_NE(), not DCHECK_NE().

This is a follow-up to e54c80cf9ba129b943eed6af3266899753b1b4ac.

P.S.
  This also fixes C++ build on macOS 14.5 for this 1.17.x branch with
  Xcode 15.3.  There was a linker error like below without this patch:

    Undefined symbols for architecture x86_64:
      "void google::MakeCheckOpValueString<std::nullptr_t>(std::__1::basic_ostream<char, std::__1::char_traits<char>>*, std::nullptr_t const&)", referenced from:
	  std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>* google::MakeCheckOpString<std::nullptr_t, kudu::cluster::ExternalTabletServer*>(std::nullptr_t const&, kudu::cluster::ExternalTabletServer* const&, char const*) in disk_reservation-itest.cc.o
    ld: symbol(s) not found for architecture x86_64

Change-Id: I78428cf60449820508f995c4a7c2a84582ce32c1
Reviewed-on: http://gerrit.cloudera.org:8080/21229
Tested-by: Alexey Serbin <alexey@apache.org>
Reviewed-by: Mahesh Reddy <mreddy@cloudera.com>
Reviewed-by: Abhishek Chennaka <achennaka@cloudera.com>
(cherry picked from commit ab368443d276006e93370a5b6bd5862eea2475fe)
Reviewed-on: http://gerrit.cloudera.org:8080/21919
Tested-by: Abhishek Chennaka <achennaka@cloudera.com>