ODP-7796: Extend RocksDB GCC 14 patch to fix util/string_util.h
Extended rocksdb-gcc14-cstdint.patch to also fix util/string_util.h,
which has the same missing #include <cstdint> issue:

  error: 'uint64_t' has not been declared
  error: 'uint8_t' does not name a type
  error: 'uint32_t' does not name a type
    at util/string_util.h

The patch now fixes both data_block_hash_index.h and string_util.h.